### ISSUE TITLE
Content Pack fails to install on Graylog 4.x

### ISSUE THREAD

**Issue by tmontney** [devopstales/pfsense-graylog#12]
Same issue as https://github.com/devopstales/pfsense-graylog/issues/6.

Also noticed the Download from GitHub button is broken: https://marketplace.graylog.org/addons/e2f1e6cf-e4ac-4f5b-95ae-e8f377d43187. Can't see that JSON file in newer commits.

**Comment by kevin-xue-ai** [comment]
> Same issue as #6.
> 
> Also noticed the Download from GitHub button is broken: https://marketplace.graylog.org/addons/e2f1e6cf-e4ac-4f5b-95ae-e8f377d43187. Can't see that JSON file in newer commits.

Is there a way to fix it?

**Comment by zedebugger** [comment]
Same here. How do we install on Graylog 4.x?

**Comment by devopstales** [comment]
@tmontney @kevin-xue-ai @zedebugger If you check my repository you can find a folder called pfsense_content_pack. There is the content pack json for different versions of graylog server.

**Comment by TonyBostonTB** [comment]
> @tmontney @kevin-xue-ai @zedebugger If you check my repository you can find a folder called pfsense_content_pack. There is the content pack json for different versions of graylog server.

Yeah but still, everybody was asking for v4.* - theres only v2-v3

**Comment by devopstales** [comment]
@TonyBostonTB The v3 content pack works fine with 4.0 and 4.1, but to be more obvious I linked the v4 folder to the original v3 folder. If you have problems at installing the content pack  please check your graylog log files.
