### ISSUE TITLE
Content pack for Graylog 5 and Elasticsearch 7?

### ISSUE THREAD

**Issue by tecnovi** [devopstales/pfsense-graylog#14]
Is compatible with ES7 the content pack that you have share? pfsense_content_pack/graylog5_regex/extractors/pfSense_Extractors_Firewall_2.5.0_RFC_3164.json

I have Graylog with Elasticsearch 7.

Thanks in advance!

**Comment by devopstales** [comment]
How Elasticsearch handles the extracted values is based on the index, For this there is index patterns under Elasticsearch_pfsense_custom_template/
