### ISSUE TITLE
The dashboard not working latest grafana

### ISSUE THREAD

**Issue by weinix** [devopstales/pfsense-graylog#3]
Thanks for your work!
Is there a updated dashboard json file with latest Grafana? It appears the current version of dashboard is no longer compatible with latest version of grafana.
Thanks again.

**Comment by devopstales** [comment]
I will test it with the new Grafana, but it would  be easier if you cud get me your Grafana version.

**Comment by weinix** [comment]
Thank you for prompt response!
My bad, I assumed I installed it recently and got latest version. My grafana environment is a jail on freenas and the installed version is actually very old, 4.6.5. Sorry!
I just tested with docker with grafana version 6.3.5 and it worked like charm!
Appreciate your great work!
