### ISSUE TITLE
GROK patterns fail to parse interfaces with "." like VLAN interfaces

### ISSUE THREAD

**Issue by AndLindemann** [devopstales/pfsense-graylog#4]
Filterlog messages like:
`199,,,1582642731,vtnet0.99,match,pass,in,4,0x0,,64,16922,0,DF,17,udp,65,10.0.99.20,10.0.99.1,56672,53,45`
cannot be parsed by the grok patterns, as interfaces are defined as WORD and WORD does not contain the "." character.
Instead for me I changed grok pattern PFSENSE_LOG_DATA from:

`%{INT:rule},%{INT:sub_rule}?,,%{INT:tracker},%{WORD:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},`

TO
`%{INT:rule},%{INT:sub_rule}?,,%{INT:tracker},%{USERNAME:iface},%{WORD:reason},%{WORD:action},%{WORD:direction},`

USERNAME allows for mostly similar characters to WORD but also contains the ".", allowing the pattern to be matched in case the interface is a VLAN interface.

**Comment by devopstales** [comment]
Cosing in favor of https://github.com/devopstales/pfsense-graylog/pull/5
