### ISSUE TITLE
Question rather than issue

### ISSUE THREAD

**Issue by lo-el** [devopstales/pfsense-graylog#7]
Hi there, thank you for keeping this up-to-date. 

I need to ask if there is particular reason I dont have the log files from pfsense shown in graylog. Is this pack only for graphana implementation? 

note that raw inputs work just fine.

If it's that the case can you please point me a way to display the log messages also in graylog ? thank you (

Thank you for your effort

**Comment by devopstales** [comment]
You can find all the log sent by pfsense in the stream called pfsense. @lo-el
