### ISSUE TITLE
Compatibility With OPNsense?

### ISSUE THREAD

**Issue by Cust0mfirmware** [devopstales/pfsense-graylog#8]
* **Expected behavior**
Since OPNsense is a fork of pfsense and the content pack in the graylog marketplace has a "OPNsense" tag, I thought that this project should also work on the current of OPNsense (e.g. the logs are parsed correctly within graylog).

* **Current behavior**
Logs are sent to graylog as expected, but almost no field but "level" and "facility" is parsed correctly:
![graylog](https://user-images.githubusercontent.com/25750652/96362037-c10bb280-112a-11eb-8014-2e52d3e0c09c.png)

The log messages seem to have a different format:
`opnsense.lan.localdomain filterlog[74604]: 66,,,0,wg0,match,pass,out,4,0x0,,63,26087,0,DF,17,udp,675,192.168.0.2,192.168.1.15,37160,8089,655`

* **Environment**
* OPNsense 20.7.3-amd64
* Graylog v3.3.8+e223f85
* elasticsearch-oss:6.8.10
* cerebro 0.9.2

Is there any way to get this great project working with the current version of OPNsense?

**Comment by devopstales** [comment]
@Cust0mfirmware I modified the template to work with Opnsense. It was easy. In the extractor the condition was `filterlog:` but Opensese use a different format:
```
# opnsense
opnsense.mydomain.intra filterlog[74604]: 66,,,0,wg0,match,pass,out,4,0x0,,63,26087,0,DF,17,udp,675,192.168.0.2,192.168.1.15,37160,8089,655
# pfsense
pfsense.mydomain.intra filterlog: 48,,,1000008011,igb0,match,pass,out,4,0x0,,64,33509,0,none,17,udp,98,91.208.36.136,8.8.4.4,50877,53,78
```

![graylog-opnsense](https://user-images.githubusercontent.com/42894256/97607158-ee9d0980-1a10-11eb-957f-86dec8e40b5d.png)
