### ISSUE TITLE
does nto

### ISSUE THREAD

**Issue by davkar3n** [devopstales/pfsense-graylog#9]
pf_custom json does not support elasticsearch-oss/stable,now 7.10.0 and cerebro 0.9.3

**Comment by wedge1001** [comment]
I faced the same problem. 
In elasticsearch 7.x the mapping types have been deprecated. You can get it to work like this, without using cerebro
```
curl -X PUT "localhost:9200/_template/pfsense_custom?include_type_name=true&pretty" -H 'Content-Type: application/json' -d'
{
  "order": -1,
  "template": "pfsense_*",
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "analyzer_keyword": {
            "filter": "lowercase",
            "tokenizer": "keyword"
          }
        }
      },
      "max_result_window": "1000000"
    }
  },
 "mappings": {
    "message": {
      "properties": {
        "PFSENSE_ICMP_DATA": {
          "type": "keyword"
        },
        "PFSENSE_ICMP_ECHO_REQ_REPLY": {
          "type": "keyword"
        },
        "PFSENSE_ICMP_RESPONSE": {
          "type": "keyword"
        },
        "PFSENSE_ICMP_TYPE": {
          "type": "keyword"
        },
        "PFSENSE_ICMP_UNREACHPORT": {
          "type": "keyword"
        },
        "PFSENSE_IGMP_DATA": {
          "type": "keyword"
        },
        "PFSENSE_IP_DATA": {
          "type": "keyword"
        },
        "PFSENSE_IP_SPECIFIC_DATA": {
          "type": "keyword"
        },
        "PFSENSE_IPv4_SPECIFIC_DATA": {
          "type": "keyword"
        },
        "PFSENSE_LOG_DATA": {
          "type": "keyword"
        },
        "PFSENSE_LOG_ENTRY": {
          "type": "keyword"
        },
        "PFSENSE_PROTOCOL_DATA": {
          "type": "keyword"
        },
        "PFSENSE_TCP_DATA": {
          "type": "keyword"
        },
        "PFSENSE_UDP_DATA": {
          "type": "keyword"
        },
        "ack_number": {
          "type": "keyword"
        },
        "action": {
          "type": "keyword"
        },
        "data_length": {
          "type": "keyword"
        },
        "dest_ip": {
          "type": "keyword"
        },
        "dest_ip_city_name": {
          "type": "keyword"
        },
        "dest_ip_country_code": {
          "type": "keyword"
        },
        "dest_ip_geolocation": {
          "type": "text",
          "copy_to": "dst_location"
        },
        "dst_location": {
          "type": "geo_point"
        },
        "dest_port": {
          "type": "keyword"
        },
        "direction": {
          "type": "keyword"
        },
        "ecn": {
          "type": "keyword"
        },
        "facility": {
          "type": "keyword"
        },
        "flags": {
          "type": "keyword"
        },
        "full_message": {
          "type": "text",
          "analyzer": "standard"
        },
        "gl2_remote_ip": {
          "type": "keyword"
        },
        "gl2_remote_port": {
          "type": "keyword"
        },
        "gl2_source_input": {
          "type": "keyword"
        },
        "gl2_source_node": {
          "type": "keyword"
        },
        "icmp_echo_id": {
          "type": "keyword"
        },
        "icmp_echo_sequence": {
          "type": "keyword"
        },
        "icmp_type": {
          "type": "keyword"
        },
        "icmp_unreachport_dest_ip": {
          "type": "keyword"
        },
        "icmp_unreachport_dest_ip_city_name": {
          "type": "keyword"
        },
        "icmp_unreachport_dest_ip_country_code": {
          "type": "keyword"
        },
        "icmp_unreachport_dest_ip_geolocation": {
          "type": "keyword"
        },
        "icmp_unreachport_port": {
          "type": "keyword"
        },
        "icmp_unreachport_protocol": {
          "type": "keyword"
        },
        "id": {
          "type": "keyword"
        },
        "iface": {
          "type": "keyword"
        },
        "ip_ver": {
          "type": "keyword"
        },
        "length": {
          "type": "keyword"
        },
        "level": {
          "type": "long"
        },
        "message": {
          "type": "text",
          "analyzer": "standard"
        },
        "offset": {
          "type": "keyword"
        },
        "proto": {
          "type": "keyword"
        },
        "proto_id": {
          "type": "keyword"
        },
        "reason": {
          "type": "keyword"
        },
        "rule": {
          "type": "keyword"
        },
        "sequence_number": {
          "type": "keyword"
        },
        "source": {
          "type": "text",
          "analyzer": "analyzer_keyword",
          "fielddata": true
        },
        "src_ip": {
          "type": "keyword"
        },
        "src_ip_city_name": {
          "type": "keyword"
        },
        "src_ip_country_code": {
          "type": "keyword"
        },
        "src_ip_geolocation": {
          "type": "text",
          "copy_to": "src_location"
        },
        "src_location": {
          "type": "geo_point"
        },
        "src_port": {
          "type": "keyword"
        },
        "streams": {
          "type": "keyword"
        },
        "tcp_flags": {
          "type": "keyword"
        },
        "tcp_options": {
          "type": "keyword"
        },
        "tcp_window": {
          "type": "keyword"
        },
        "timestamp": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss.SSS"
        },
        "real_timestamp": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "tos": {
          "type": "keyword"
        },
        "tracker": {
          "type": "keyword"
        },
        "ttl": {
          "type": "keyword"
        }
      },
      "dynamic_templates": [
        {
          "internal_fields": {
            "match": "gl2_*",
            "mapping": {
              "type": "keyword"
            }
          }
        },
        {
          "store_generic": {
            "match": "*",
            "mapping": {
              "index": "true"
            }
          }
        }
      ],
      "_source": {
        "enabled": true
      }
    }
  },
  "aliases": {}
}
'
```

**Comment by Sub-SH** [comment]
@wedge1001 I'm having an issue with your solution. I'm using Graylog 4.0 and Elasticsearch 7.10. I'm also using Cerebro to input the file, but I'm getting this error:

`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [message : {_source={enabled=true}, dynamic_templates=[{internal_fields={mapping={type=keyword}, match=gl2_*}}, {store_generic={mapping={index=true}, match=*}}], properties={PFSENSE_UDP_DATA={type=keyword}, reason={type=keyword}, gl2_remote_ip={type=keyword}, gl2_remote_port={type=keyword}, icmp_unreachport_dest_ip={type=keyword}, icmp_unreachport_protocol={type=keyword}, dest_ip_geolocation={copy_to=dst_location, type=text}, source={fielddata=true, analyzer=analyzer_keyword, type=text}, gl2_source_input={type=keyword}, PFSENSE_ICMP_ECHO_REQ_REPLY={type=keyword}, PFSENSE_PROTOCOL_DATA={type=keyword}, ack_number={type=keyword}, ip_ver={type=keyword}, ecn={type=keyword}, dest_ip_city_name={type=keyword}, tcp_flags={type=keyword}, PFSENSE_ICMP_UNREACHPORT={type=keyword}, PFSENSE_ICMP_DATA={type=keyword}, src_ip_city_name={type=keyword}, action={type=keyword}, gl2_source_node={type=keyword}, id={type=keyword}, src_ip_geolocation={copy_to=src_location, type=text}, dest_port={type=keyword}, PFSENSE_IGMP_DATA={type=keyword}, offset={type=keyword}, level={type=long}, streams={type=keyword}, PFSENSE_TCP_DATA={type=keyword}, PFSENSE_ICMP_RESPONSE={type=keyword}, icmp_unreachport_dest_ip_geolocation={type=keyword}, PFSENSE_ICMP_TYPE={type=keyword}, iface={type=keyword}, tcp_window={type=keyword}, icmp_unreachport_port={type=keyword}, icmp_echo_id={type=keyword}, dest_ip={type=keyword}, proto={type=keyword}, PFSENSE_LOG_DATA={type=keyword}, icmp_type={type=keyword}, PFSENSE_IPv4_SPECIFIC_DATA={type=keyword}, flags={type=keyword}, rule={type=keyword}, PFSENSE_IP_DATA={type=keyword}, icmp_unreachport_dest_ip_city_name={type=keyword}, tcp_options={type=keyword}, PFSENSE_IP_SPECIFIC_DATA={type=keyword}, src_ip={type=keyword}, PFSENSE_LOG_ENTRY={type=keyword}, proto_id={type=keyword}, tracker={type=keyword}, tos={type=keyword}, direction={type=keyword}, timestamp={format=yyyy-MM-dd HH:mm:ss.SSS, type=date}, data_length={type=keyword}, length={type=keyword}, icmp_unreachport_dest_ip_country_code={type=keyword}, message={analyzer=standard, type=text}, ttl={type=keyword}, icmp_echo_sequence={type=keyword}, sequence_number={type=keyword}, src_location={type=geo_point}, src_port={type=keyword}, dest_ip_country_code={type=keyword}, dst_location={type=geo_point}, src_ip_country_code={type=keyword}, full_message={analyzer=standard, type=text}, facility={type=keyword}, real_timestamp={format=yyyy-MM-dd HH:mm:ss, type=date}}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [message : {_source={enabled=true}, dynamic_templates=[{internal_fields={mapping={type=keyword}, match=gl2_*}}, {store_generic={mapping={index=true}, match=*}}], properties={PFSENSE_UDP_DATA={type=keyword}, reason={type=keyword}, gl2_remote_ip={type=keyword}, gl2_remote_port={type=keyword}, icmp_unreachport_dest_ip={type=keyword}, icmp_unreachport_protocol={type=keyword}, dest_ip_geolocation={copy_to=dst_location, type=text}, source={fielddata=true, analyzer=analyzer_keyword, type=text}, gl2_source_input={type=keyword}, PFSENSE_ICMP_ECHO_REQ_REPLY={type=keyword}, PFSENSE_PROTOCOL_DATA={type=keyword}, ack_number={type=keyword}, ip_ver={type=keyword}, ecn={type=keyword}, dest_ip_city_name={type=keyword}, tcp_flags={type=keyword}, PFSENSE_ICMP_UNREACHPORT={type=keyword}, PFSENSE_ICMP_DATA={type=keyword}, src_ip_city_name={type=keyword}, action={type=keyword}, gl2_source_node={type=keyword}, id={type=keyword}, src_ip_geolocation={copy_to=src_location, type=text}, dest_port={type=keyword}, PFSENSE_IGMP_DATA={type=keyword}, offset={type=keyword}, level={type=long}, streams={type=keyword}, PFSENSE_TCP_DATA={type=keyword}, PFSENSE_ICMP_RESPONSE={type=keyword}, icmp_unreachport_dest_ip_geolocation={type=keyword}, PFSENSE_ICMP_TYPE={type=keyword}, iface={type=keyword}, tcp_window={type=keyword}, icmp_unreachport_port={type=keyword}, icmp_echo_id={type=keyword}, dest_ip={type=keyword}, proto={type=keyword}, PFSENSE_LOG_DATA={type=keyword}, icmp_type={type=keyword}, PFSENSE_IPv4_SPECIFIC_DATA={type=keyword}, flags={type=keyword}, rule={type=keyword}, PFSENSE_IP_DATA={type=keyword}, icmp_unreachport_dest_ip_city_name={type=keyword}, tcp_options={type=keyword}, PFSENSE_IP_SPECIFIC_DATA={type=keyword}, src_ip={type=keyword}, PFSENSE_LOG_ENTRY={type=keyword}, proto_id={type=keyword}, tracker={type=keyword}, tos={type=keyword}, direction={type=keyword}, timestamp={format=yyyy-MM-dd HH:mm:ss.SSS, type=date}, data_length={type=keyword}, length={type=keyword}, icmp_unreachport_dest_ip_country_code={type=keyword}, message={analyzer=standard, type=text}, ttl={type=keyword}, icmp_echo_sequence={type=keyword}, sequence_number={type=keyword}, src_location={type=geo_point}, src_port={type=keyword}, dest_ip_country_code={type=keyword}, dst_location={type=geo_point}, src_ip_country_code={type=keyword}, full_message={analyzer=standard, type=text}, facility={type=keyword}, real_timestamp={format=yyyy-MM-dd HH:mm:ss, type=date}}}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [message : {_source={enabled=true}, dynamic_templates=[{internal_fields={mapping={type=keyword}, match=gl2_*}}, {store_generic={mapping={index=true}, match=*}}], properties={PFSENSE_UDP_DATA={type=keyword}, reason={type=keyword}, gl2_remote_ip={type=keyword}, gl2_remote_port={type=keyword}, icmp_unreachport_dest_ip={type=keyword}, icmp_unreachport_protocol={type=keyword}, dest_ip_geolocation={copy_to=dst_location, type=text}, source={fielddata=true, analyzer=analyzer_keyword, type=text}, gl2_source_input={type=keyword}, PFSENSE_ICMP_ECHO_REQ_REPLY={type=keyword}, PFSENSE_PROTOCOL_DATA={type=keyword}, ack_number={type=keyword}, ip_ver={type=keyword}, ecn={type=keyword}, dest_ip_city_name={type=keyword}, tcp_flags={type=keyword}, PFSENSE_ICMP_UNREACHPORT={type=keyword}, PFSENSE_ICMP_DATA={type=keyword}, src_ip_city_name={type=keyword}, action={type=keyword}, gl2_source_node={type=keyword}, id={type=keyword}, src_ip_geolocation={copy_to=src_location, type=text}, dest_port={type=keyword}, PFSENSE_IGMP_DATA={type=keyword}, offset={type=keyword}, level={type=long}, streams={type=keyword}, PFSENSE_TCP_DATA={type=keyword}, PFSENSE_ICMP_RESPONSE={type=keyword}, icmp_unreachport_dest_ip_geolocation={type=keyword}, PFSENSE_ICMP_TYPE={type=keyword}, iface={type=keyword}, tcp_window={type=keyword}, icmp_unreachport_port={type=keyword}, icmp_echo_id={type=keyword}, dest_ip={type=keyword}, proto={type=keyword}, PFSENSE_LOG_DATA={type=keyword}, icmp_type={type=keyword}, PFSENSE_IPv4_SPECIFIC_DATA={type=keyword}, flags={type=keyword}, rule={type=keyword}, PFSENSE_IP_DATA={type=keyword}, icmp_unreachport_dest_ip_city_name={type=keyword}, tcp_options={type=keyword}, PFSENSE_IP_SPECIFIC_DATA={type=keyword}, src_ip={type=keyword}, PFSENSE_LOG_ENTRY={type=keyword}, proto_id={type=keyword}, tracker={type=keyword}, tos={type=keyword}, direction={type=keyword}, timestamp={format=yyyy-MM-dd HH:mm:ss.SSS, type=date}, data_length={type=keyword}, length={type=keyword}, icmp_unreachport_dest_ip_country_code={type=keyword}, message={analyzer=standard, type=text}, ttl={type=keyword}, icmp_echo_sequence={type=keyword}, sequence_number={type=keyword}, src_location={type=geo_point}, src_port={type=keyword}, dest_ip_country_code={type=keyword}, dst_location={type=geo_point}, src_ip_country_code={type=keyword}, full_message={analyzer=standard, type=text}, facility={type=keyword}, real_timestamp={format=yyyy-MM-dd HH:mm:ss, type=date}}}]"
    }
  },
  "status": 400
}`

**Comment by devopstales** [comment]
Fixed with a new EL template. @IamAliBaba @subterminal
